# Generated by Django 4.2.1 on 2023-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('price_englishelm', models.CharField(blank=True, max_length=200)),
                ('price_livaroom', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(max_length=200)),
            ],
        ),
    ]
