# Generated by Django 4.2.1 on 2023-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('variant_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('handle', models.CharField(max_length=200)),
                ('price_englishelm', models.CharField(blank=True, max_length=200)),
                ('price_livaroom', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(max_length=200)),
                ('featured_image', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('price_englishelm', models.CharField(blank=True, max_length=200)),
                ('price_livaroom', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(max_length=200)),
            ],
        ),
    ]
