# Generated by Django 4.2.1 on 2023-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('handle', models.CharField(max_length=200)),
                ('price_englishelm', models.CharField(blank=True, max_length=200)),
                ('price_livaroom', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(max_length=200)),
            ],
        ),
    ]
