# Generated by Django 4.2.1 on 2023-05-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
