# Generated by Django 4.2.1 on 2023-06-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_coleman',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
