# Generated by Django 4.2.1 on 2023-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_coleman'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_1stopbedrooms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url_1stopbedrooms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
